#!/usr/bin/env bash
# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
#
# One-time (idempotent) host setup for TheRock + FASTBuild inside a minimal
# Ubuntu-based Slurm/Pyxis container (e.g. ghcr.io/rocm/no_rocm_image_ubuntu24_04).
#
# Usage (inside the container, from anywhere):
#   bash /path/to/TheRock/build_tools/fastbuild_container_setup.sh
#   source ~/.therock-fastbuild-env/activate.sh
#
# Environment:
#   THEROCK_SLIM_ENV_ROOT   Install prefix root (default: $HOME/.therock-fastbuild-env)
#   THEROCK_REPO            TheRock checkout (default: parent of this script's dir)
#   CMAKE_VERSION           Kitware CMake version (default: 4.2.3)
#   FASTBUILD_VERSION       FASTBuild release (default: 1.20)
#   FORCE=1                 Re-run all install steps even if stamp matches

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEROCK_REPO="${THEROCK_REPO:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
ENV_ROOT="${THEROCK_SLIM_ENV_ROOT:-${HOME}/.therock-fastbuild-env}"
OPT_PREFIX="${ENV_ROOT}/opt"
STAMP="${ENV_ROOT}/.setup-stamp"
CMAKE_VERSION="${CMAKE_VERSION:-4.2.3}"
FASTBUILD_VERSION="${FASTBUILD_VERSION:-1.20}"

FORCE="${FORCE:-0}"

log() {
  printf '%s\n' "$*" >&2
}

run_apt() {
  local cmd=("$@")
  if [[ "$(id -u)" -eq 0 ]]; then
    "${cmd[@]}"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "${cmd[@]}"
  else
    log "error: need root or sudo to run apt-get"
    exit 1
  fi
}

want_force() {
  [[ "${FORCE}" == "1" ]]
}

stamp_matches() {
  [[ -f "${STAMP}" ]] && [[ "$(cat "${STAMP}")" == "${STAMP_CONTENT}" ]]
}

STAMP_CONTENT="v5 cmake=${CMAKE_VERSION} fb=${FASTBUILD_VERSION}"

if stamp_matches && ! want_force; then
  log "Setup already done (${STAMP_CONTENT}). Source:"
  log "  source ${ENV_ROOT}/activate.sh"
  exit 0
fi

mkdir -p "${OPT_PREFIX}/bin" "${ENV_ROOT}/tmp"
export PATH="${OPT_PREFIX}/bin:${PATH}"

log "==> TheRock container setup"
log "    THEROCK_REPO=${THEROCK_REPO}"
log "    ENV_ROOT=${ENV_ROOT}"

log "==> apt packages (TheRock README + FASTBuild/sysdeps helpers)"
run_apt apt-get update -y
run_apt apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  make \
  unzip \
  wget \
  g++ \
  gcc \
  gfortran \
  pkg-config \
  python3 \
  python3-dev \
  python3-venv \
  ninja-build \
  xxd \
  automake \
  autoconf \
  autoconf-archive \
  libtool \
  flex \
  bison \
  m4 \
  meson \
  patchelf \
  texinfo \
  libegl1-mesa-dev \
  zlib1g-dev \
  liblzma-dev \
  libzstd-dev \
  file

log "==> Kitware CMake ${CMAKE_VERSION} -> ${OPT_PREFIX}"
CMAKE_SH="cmake-${CMAKE_VERSION}-linux-x86_64.sh"
CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_SH}"
(
  cd "${ENV_ROOT}/tmp"
  if [[ ! -f "${CMAKE_SH}" ]] || want_force; then
    wget -q --show-progress -O "${CMAKE_SH}" "${CMAKE_URL}"
  fi
  chmod +x "${CMAKE_SH}"
  "./${CMAKE_SH}" --skip-license --prefix="${OPT_PREFIX}"
)
cmake --version

log "==> FASTBuild ${FASTBUILD_VERSION} -> ${OPT_PREFIX}/bin (fbuild + worker)"
(
  cd "${ENV_ROOT}/tmp"
  FB_ZIP="FASTBuild-Linux-x64-v${FASTBUILD_VERSION}.zip"
  FB_URL="https://fastbuild.org/downloads/v${FASTBUILD_VERSION}/${FB_ZIP}"
  if [[ ! -f "${FB_ZIP}" ]] || want_force; then
    wget -q --show-progress -O "${FB_ZIP}" "${FB_URL}"
  fi
  file "${FB_ZIP}" | grep -q Zip || {
    log "error: ${FB_ZIP} is not a zip (bad URL or proxy HTML?)"
    exit 1
  }
  UNPACK="${ENV_ROOT}/tmp/fastbuild-${FASTBUILD_VERSION}-unpacked"
  rm -rf "${UNPACK}"
  mkdir -p "${UNPACK}"
  unzip -o -q "${FB_ZIP}" -d "${UNPACK}"

  FBUILD_SRC="$(find "${UNPACK}" -type f \( -name fbuild -o -name FBuild \) | head -n1)"
  if [[ -z "${FBUILD_SRC}" ]]; then
    log "error: could not find fbuild in ${FB_ZIP} (see unzip -l ${FB_ZIP})"
    exit 1
  fi
  install -m 0755 "${FBUILD_SRC}" "${OPT_PREFIX}/bin/fbuild"

  WORKER_SRC="$(find "${UNPACK}" -type f \( -iname fbuildworker -o -iname FBuildWorker \) | head -n1)"
  if [[ -z "${WORKER_SRC}" ]]; then
    log "error: could not find fbuildworker/FBuildWorker in ${FB_ZIP}"
    log "Listing archive:"
    unzip -l "${FB_ZIP}" >&2 || true
    exit 1
  fi
  install -m 0755 "${WORKER_SRC}" "${OPT_PREFIX}/bin/fbuildworker"
  ln -sf fbuildworker "${OPT_PREFIX}/bin/FBuildWorker"
)
fbuild -version
test -x "${OPT_PREFIX}/bin/fbuildworker"

if [[ -f "${THEROCK_REPO}/dockerfiles/install_pinned_patchelf.sh" ]]; then
  log "==> pinned patchelf (TheRock dockerfiles) -> ${OPT_PREFIX}"
  (
    work="$(mktemp -d)"
    trap 'rm -rf "${work}"' EXIT
    cd "${work}"
    INSTALL_PREFIX="${OPT_PREFIX}" bash "${THEROCK_REPO}/dockerfiles/install_pinned_patchelf.sh"
  )
else
  log "warning: skip pinned patchelf (missing ${THEROCK_REPO}/dockerfiles/install_pinned_patchelf.sh)"
fi

cat >"${ENV_ROOT}/activate.sh" <<EOF
# Generated by fastbuild_container_setup.sh — source in bash/zsh
export THEROCK_SLIM_ENV_ROOT="${ENV_ROOT}"
export PATH="${OPT_PREFIX}/bin:\${PATH}"
EOF

printf '%s\n' "${STAMP_CONTENT}" >"${STAMP}"

log ""
log "Done. For every new shell in the container:"
log "  source ${ENV_ROOT}/activate.sh"
log ""
log "Then in your TheRock clone:"
log "  python3 -m venv .venv && source .venv/bin/activate"
log "  pip install -r requirements.txt"
log "  python3 ./build_tools/fetch_sources.py"
